-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Sales transaction"
(
    transaction_id integer NOT NULL,
    "Date" date,
    "Time" timestamp without time zone,
    "Sales_outlet" character varying(100),
    "Staff" character varying(100),
    "Customer" character varying(100),
    PRIMARY KEY (None)
);

CREATE TABLE IF NOT EXISTS public."Product"
(
    "Producr_id" integer NOT NULL,
    "Type" character varying,
    "Description" character varying,
    "Price" double precision,
    PRIMARY KEY ("Producr_id")
);

CREATE TABLE IF NOT EXISTS public.sales_detail
(
    sales_detail_id integer NOT NULL,
    transaction_id integer,
    product_id integer,
    quantity integer,
    price double precision,
    PRIMARY KEY (sales_detail_id)
);

CREATE TABLE IF NOT EXISTS public.product_type
(
    product_type_id integer NOT NULL,
    product_category integer,
    product_type integer,
    PRIMARY KEY (product_type_id)
);

ALTER TABLE IF EXISTS public."Sales transaction"
    ADD FOREIGN KEY (transaction_id)
    REFERENCES public.sales_detail (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product"
    ADD FOREIGN KEY ("Producr_id")
    REFERENCES public.sales_detail (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product"
    ADD FOREIGN KEY ("Producr_id")
    REFERENCES public.product_type (product_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;