version: '3.8'

services:
  python-app:
    image: python:3.9-slim
    container_name: python-db2-app
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud"
      DB_PORT: "31198"
      DB_NAME: "bludb"
      DB_USER: "ntl37931"
      DB_PASSWORD: "FwKvENnX6EuSoPxw"
    command: >
      sh -c "pip install ibm_db flask &&
             python index.py"

            